/**
 * Generated by scripts/sync-fairpay-docs.sh — do not edit in FairPay-docs.
 */
window.FAIRPAY_SHARE_CONFIG = {
  supabaseUrl: 'https://egblicmnlejlmkubptwu.supabase.co',
  supabaseAnonKey: 'sb_publishable_a37721qjwUWK-3ru9k-d2A_OdP_7DoJ',
  appStoreUrl: 'https://apps.apple.com/app/id6761960918',
  docsBaseUrl: 'https://docs.fairpay.nimtech.xyz',
};
